from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Job_Dataset(models.Model):
    id = models.AutoField(primary_key=True)
    JobTitle = models.CharField(max_length=131)
    Company= models.CharField(max_length=255)
    Location= models.CharField(max_length=14)
    PostDate= models.DateField(max_length=30)
    ExtractDate= models.DateField(max_length=130, null=True)
    Summary= models.CharField(max_length=131)
    Salary= models.CharField(max_length=132)
    experienceRequired = models.CharField(max_length=10, null=True, blank=True)
    JobUrl=models.CharField(max_length=133, null=True)
class Signup(models.Model):
    sno = models.AutoField(primary_key=True)
    username = models.CharField(max_length=131)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=14)
    role_select = models.CharField(max_length=30)
    phone_number = models.IntegerField()
    password = models.CharField(max_length=130)
    again_password = models.CharField(max_length=131)
    timeStamp = models.DateTimeField(auto_now_add=True,blank=True)
class UserResumes(models.Model):
    id = models.AutoField(primary_key=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=1000,default="" ,null=True)
    lastname = models.CharField(max_length=50,default="" ,null=True)
    mobile=models.CharField(max_length=100,default="" ,null=True)
    email=models.CharField(max_length=50,default="" ,null=True)
    objective = models.CharField(max_length=1000,default="" ,null=True)
    address = models.CharField(max_length=5000,default="" ,null=True)
    skill = models.TextField(max_length=5000,default="" ,null=True)
    companylocation = models.TextField(max_length=5000,default="" ,null=True)
    experience = models.CharField(max_length=3000,default="" ,null=True)
    description = models.TextField(max_length=3000,default="" ,null=True)
    degreename1 = models.CharField(max_length=1000,default="" ,null=True)
    collegename = models.CharField(max_length=1000,default="" ,null=True)
    marks = models.CharField(default="" ,max_length=100,null=True)
    cgpas = models.CharField(default="",max_length=100 ,null=True)
    degreename2 = models.CharField(max_length=1000, default="", null=True)
    universityname = models.CharField(max_length=1000, default="", null=True)
    # startdate1 = models.DateField(max_length=1000, default="", null=True)
    # startdate2 = models.DateField(max_length=1000, default="", null=True)
    # enddate1 = models.DateField(max_length=1000, default="", null=True)
    # enddate2 = models.DateField(max_length=1000, default="", null=True)
# class Customers(models.Model):
#     id=models.AutoField(primary_key=True)
#     first_name = models.CharField(max_length=200)
#     last_name = models.CharField(max_length=200)
#     email = models.CharField(max_length=200)
#     education  = models.CharField(max_length=200)
#     address = models.TextField()
#     summary = models.TextField()
#     communication = models.TextField()
#     job_title = models.CharField(max_length=200)
#     job_position = models.CharField(max_length=200)
#     comp_name = models.CharField(max_length=200)
class JobPublish(models.Model):
    id = models.AutoField(primary_key=True)
    JobTitles = models.CharField(max_length=131)
    Companys= models.CharField(max_length=255)
    Locations= models.CharField(max_length=14)
    PostDates= models.CharField(max_length=30)
    # ExtractDates= models.CharField(max_length=130)
    Summarys= models.CharField(max_length=131)
    Salarys= models.CharField(max_length=132)
class template(models.Model):
    select = models.CharField(max_length=20)