# Generated by Django 2.2.13 on 2021-06-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiverFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverFriend', to='friend.Profile')),
                ('senderFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderFriend', to='friend.Profile')),
            ],
        ),
    ]
