# Generated by Django 2.2.13 on 2021-06-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageValue', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('messageReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageReceiver', to='friend.Profile')),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSender', to='friend.Profile')),
            ],
        ),
    ]
