# Generated by Django 2.2.13 on 2021-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='msgStatus',
            field=models.CharField(default='unread', max_length=10),
        ),
    ]
