# Generated by Django 3.2 on 2021-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Recommendation', '0005_userresumes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresumes',
            name='id',
        ),
        migrations.AddField(
            model_name='userresumes',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
