# Generated by Django 3.2 on 2021-05-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Recommendation', '0006_auto_20210509_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresumes',
            old_name='sno',
            new_name='id',
        ),
    ]
