# Generated by Django 2.2.13 on 2021-06-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Recommendation', '0010_auto_20210603_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_dataset',
            name='ExtractDate',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='job_dataset',
            name='JobUrl',
            field=models.CharField(max_length=133, null=True),
        ),
    ]
