# Generated by Django 2.2.13 on 2021-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Recommendation', '0012_job_dataset_experiencerequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_dataset',
            name='ExtractDate',
            field=models.DateField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='job_dataset',
            name='PostDate',
            field=models.DateField(max_length=30),
        ),
    ]
